# Site settings
title: somecode 
email: 
description: > # this means to ignore newlines until "baseurl:"
    music and code
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codybara.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: sayon 

# Build settings
markdown: kramdown
